-- 1
SELECT DISTINCT C.NOME_CLIENTE AS 'Nome' , C.EMAIL AS 'Email', E.CIDADE AS 'Cidade'
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.FK_ID_CLIENTE
INNER JOIN MOVIMENTO_FINANCEIRO MF
ON C.ID_CLIENTE = MF.FK_ID_CLIENTE
WHERE MONTH(MF.DATA_MOVIMENTO) NOT LIKE MONTH(CURDATE());

-- 2
SELECT C.NOME_CLIENTE AS 'Nome do Cliente', C.EMAIL AS 'Email do Cliente',
MAX(MF.VALOR) AS 'Maior Valor Movimentado' FROM MOVIMENTO_FINANCEIRO MF
INNER JOIN CLIENTE C
ON C.ID_CLIENTE = MF.FK_ID_CLIENTE
GROUP BY MF.FK_ID_CLIENTE
ORDER BY ROUND(SUM(VALOR),2) DESC LIMIT 5;

-- 3
SELECT DAY(DATA_MOVIMENTO) AS 'Dia mais movimentado' 
FROM MOVIMENTO_FINANCEIRO
WHERE MONTH(DATA_MOVIMENTO) = 8
ORDER BY VALOR DESC LIMIT 1;

-- 4
DELETE FROM CLIENTE 
WHERE CPF = "111.111.111-11";

-- SELECT * FROM CLIENTE;
-- SELECT * FROM ENDERECO;
-- SELECT * FROM ID_CLIENTE_CONTA;
-- SELECT * FROM CONTA_CORRENTE;
-- SELECT * FROM MOVIMENTO_FINANCEIRO WHERE FK_ID_CLIENTE = 1;

-- 5
DELIMITER $$
CREATE TRIGGER VERIFICA_SEGURANCA BEFORE INSERT 
ON MOVIMENTO_FINANCEIRO FOR EACH ROW
BEGIN
IF ((NEW.VALOR * 3) >= (SELECT VALOR FROM MOVIMENTO_FINANCEIRO MF WHERE MF.FK_ID_CLIENTE = NEW.FK_ID_CLIENTE ORDER BY VALOR DESC LIMIT 1) AND
(SELECT COUNT(*) FROM MOVIMENTO_FINANCEIRO MF WHERE MF.FK_ID_CLIENTE = NEW.FK_ID_CLIENTE ORDER BY VALOR DESC LIMIT 1) > 10) THEN
UPDATE CONTA_CORRENTE CC SET STATUS_CONTA = 'Bloqueado' WHERE CC.FK_ID_CLIENTE = NEW.FK_ID_CLIENTE;
END IF;
END $$

DELIMITER $$
CREATE TRIGGER VERIFICA_BLOQUEIO BEFORE INSERT 
ON MOVIMENTO_FINANCEIRO FOR EACH ROW
BEGIN
IF ((SELECT DISTINCT CC.STATUS_CONTA FROM CONTA_CORRENTE CC INNER JOIN MOVIMENTO_FINANCEIRO MF 
ON CC.FK_ID_CLIENTE = MF.FK_ID_CLIENTE WHERE CC.FK_ID_CLIENTE = NEW.FK_ID_CLIENTE AND CC.STATUS_CONTA = 'Bloqueado') = 'Bloqueado') THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "Cliente com bloqueio, entre em contato para mais informações.";
END IF;
END $$

-- Inserção de Teste
INSERT INTO MOVIMENTO_FINANCEIRO (VALOR,DATA_MOVIMENTO,CATEGORIA,FK_ID_CLIENTE,FK_ID_CONTA,DESCRICAO)
VALUES (50000.00, '2022-09-03 00:00:00', 'Veículo',4,4,'Compra de veículo novo');

-- SELECT * FROM MOVIMENTO_FINANCEIRO;
-- SELECT * FROM CONTA_CORRENTE;
